my_dict = {
    "Haryana": "Chandigarh",
    "Maharastra": "Mumbai",
    "Bihar": "Patna",
    "Punjab": "Chandigarh",
    "Uttar Pradesh":"Lucknow",
    "Madhya Pradesh":"Bhopal",
    "Rajasthan":"Jaipur",
    "Dehli":"New Dehli",
    "West Bangal":"Kolkata",
    "Andhra Pradesh":"Amravati",
    "Arunachal Pradesh":"Itanagar",
    "Assam":"Dispur",
    "Chhattisgarh":"Raipur",
    "Goa": "Panaji",
	"Gujarat":"Gandhinagar",	
    "Haryana":"Chandigarh",	
	"Himachal Pradesh":"Shimla",	
	"Jharkhand":"Ranchi",	
	"Karnataka":"Bengaluru",	
	"Kerala":"Thiruvananthapuram",	
	"Maharashtra":"Mumbai",
	"Manipur":"Imphal",
	"Meghalaya":"Shillong",	
	"Mizoram":"Aizawl",	
	"Nagaland":"Kohima",	
	"Odisha":"Bhubaneswar",	
    "Sikkim":"Gangtok",	
	"Tamil Nadu":"Chennai",	
	"Telangana":"Hyderabad",	
	"Tripura":"Agartala",	
	"Uttarakhand":"Dehradun", 

    }
State = input("Enter a State:")
print(my_dict.get(State))